export const enum BOT_STATUS {
    STATUS_BEFORE_PARTICIPATE,
    STATUS_ASSINGING_WALLET,
    STATUS_READY,
    STATUS_FAILT_ASSIGING_WALLET,
    STATUS_WAITING_TRANSFER_PARAMS,
    STATUS_DOING_TRANSFER,
    STATUS_SUCCEED_TRANSFER,
    STATUS_FAILT_TRANSFER,
    STATUS_WATING_AIRDROP_PARAMS,
    STATUS_DOING_AIRDROP,
    STATUS_SUCCEED_AIRDROP,
    STATUS_FAILT_AIRDROP,
    STATUS_WAITING_BALANCE_PARAMS,
    STATUS_READING_BALANCE,
    STATUS_SHOWING_BALANCE,
    STATUS_WAITING_WITHDRAW_PARAMS,
    STATUS_DOING_WITHDRAW,
    STATUS_SUCCEED_WITHDRAW,
    STATUS_FAILT_WITHDRAW,
}

global.BOT_STATUS = {};


